Empresa2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include('pwa.urls')),
]

admin.site.site_title = "JardineriaBMMC"
admin.site.site_header = "Administracion Jardineria BMMC"
admin.site.index_title = "Modulos de la aplicacion"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers

#todas las rutas del CRUD
#URL: api/producto
router = routers.DefaultRouter()
router.register('Producto', ProductoViewSet)
router.register('subscripcion', SubscripcionViewSet)

from  .views import agregar, modificar, eliminar, tabla

urlpatterns = [
    path('', index, name="index"),
    path('contacto/', contacto, name="contacto"),
    path('productos/', productos, name="productos"),
    path('ingreso/', ingreso, name="ingreso"),
    path('registro/', registro, name="registro"),

    #Admin
    path('agregar/', agregar, name="agregar"),
    path('modificar/<id>/', modificar, name="modificar"),
    path('eliminar/<id>/', eliminar, name="eliminar"),
    path('tabla/', tabla, name="tabla"),

    #registrarse
    path('registraruser/', registrar_user, name="registrar_user"),
    path('subscripcion/', subscripsion, name="subscripcion"),
    path('eliminar_sub/<id>/', eliminar_sub, name='eliminar_sub'),

    path('api/', include(router.urls))
]

app/models.py
from django.db import models
from django.db.models.fields import IntegerField
from django.contrib.auth.models import Permission, User

# Create your models here.

class TipoPorducto(models.Model):
    tipo = models.CharField(max_length=40)

    def __str__(self):
        return self.tipo

class Producto(models.Model):
    nombre = models.CharField(max_length=40)
    precio = models.IntegerField()
    descripcion = models.CharField(max_length=40)
    tipo = models.ForeignKey(TipoPorducto, on_delete=models.CASCADE)
    fecha = models.DateField()
    imagen = models.ImageField(null =True, blank=True)
    descuento = models.IntegerField()

    def __str__(self):
        return self.nombre

class Fundacion(models.Model):
    fundacion = models.CharField(max_length=40)
    monto_sub = models.IntegerField()
    descuento = models.IntegerField()
    def __str__(self):
        return self.fundacion

class Subscripcion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fundacion = models.ForeignKey(Fundacion, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario

#python manage.py makemigrations --- CREA EL ARCHIVO PARA MIGRAR
#python manage.py migrate --- ENVIA EL ARCHIVO A LA BD
#python manage.py createsuperuser --- CREA EL ADMIN EN LA WEB

"""
odd_even = Permission.objects.get(name='can_view_even_ids')
user_yui = User.objects.get(username='yui')
user_yui.user_permissions.add(odd_even)
user_yui.save()
"""

app/templates/app/admin/agregar.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8 p-3">
            
            <h1 class="display-4">Agregar Productos</h1>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <table class="table table-hover">
                    {{ formulario|crispy }}
                </table>
                <div class="container flex-wrap">
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-primary" value="Agregar">
                            <input type="reset" class="btn btn-danger" value="Limpiar">
                        </div>
                    </div>
                </div>
                {{ mensaje }}
            </form>
        </div>
        <div class="col-sm-2"></div>
    </div>
</div>
{% else %}
 <p>No estas logueado</p>
{% endif %}

{% endblock %}

app/templates/app/admin/modificar.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8 p-3">
            
            <h1 class="display-4">Modificar Productos</h1>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table table-hover">
                    {{ formulario|crispy }}
                </table>
                <div class="container flex-wrap">
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-primary" value="Modificar">
                            <input type="reset" class="btn btn-danger" value="Limpiar">
                        </div>
                    </div>
                </div>
                {{ mensaje }}
            </form>
        </div>
        <div class="col-sm-2"></div>
    </div>
</div>
{% else %}
<p>No estas logueado</p>
{% endif %}

{% endblock %}

app/templates/app/admin/tabla.html
{% extends 'app/base.html' %}
{% load static %}

{% block contenido %}
{% if perms.view_producto %}
<div class="container my-3 mx-3">
    <div class="row">
        {% if perms.app.add_producto %}
        <a href="{% url 'agregar' %}" class="btn btn-primary">Agregar Productos</a>
        {% else %}

        {% endif %}    
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12 py-4">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Descuento</th>
                        <th>Descripcion</th>
                        <th>Tipo</th>
                        <th>Fecha</th>
                        <th>Imagen</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for aux in tabla %}
                    <tr>
                        <td>{{ aux.nombre }}</td>
                        <td>{{ aux.precio }}</td>
                        <td>{{ aux.descuento }}%</td>
                        <td>{{ aux.descripcion }}</td>
                        <td>{{ aux.tipo }}</td>
                        <td>{{ aux.fecha }}</td>
                        <td>{% if aux.imagen %}
                            <img src="{{ aux.imagen.url }}" alt="" width="50" height="50">
                        {% else %}
                            <img src="{% static 'app/dist/img/imagen-defecto.png' %}" alt="" width="50" height="50">
                        {% endif %}
                        </td>
                        <td>
                            {% if perms.app.change_producto %}
                            <a href="{% url 'modificar' aux.id %}" class="btn btn-primary">Modificar</a>
                            {% endif %} 
                            {% if perms.app.delete_producto %}
                            <a onclick="confirmarEliminar({{ aux.id }})" class="btn btn-danger">Eliminar</a>
                            {% endif %} 
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            <div>
                {% include 'app/paginator.html' %}
            </div>
            
        </div>
    </div>
</div>
{% else %}
<p>No estas logueado</p>
{% endif %}

            
{% endblock %}

{% block javascript %}
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'app/dist/js/funcionalidades.js' %}"></script>
{% endblock %}