Empresa2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include('pwa.urls')),
]

admin.site.site_title = "JardineriaBMMC"
admin.site.site_header = "Administracion Jardineria BMMC"
admin.site.index_title = "Modulos de la aplicacion"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers

#todas las rutas del CRUD
#URL: api/producto
router = routers.DefaultRouter()
router.register('Producto', ProductoViewSet)
router.register('subscripcion', SubscripcionViewSet)

from  .views import agregar, modificar, eliminar, tabla

urlpatterns = [
    path('', index, name="index"),
    path('contacto/', contacto, name="contacto"),
    path('productos/', productos, name="productos"),
    path('ingreso/', ingreso, name="ingreso"),
    path('registro/', registro, name="registro"),

    #Admin
    path('agregar/', agregar, name="agregar"),
    path('modificar/<id>/', modificar, name="modificar"),
    path('eliminar/<id>/', eliminar, name="eliminar"),
    path('tabla/', tabla, name="tabla"),

    #registrarse
    path('registraruser/', registrar_user, name="registrar_user"),
    path('subscripcion/', subscripsion, name="subscripcion"),
    path('eliminar_sub/<id>/', eliminar_sub, name='eliminar_sub'),

    path('api/', include(router.urls))
]

app/models.py
from django.db import models
from django.db.models.fields import IntegerField
from django.contrib.auth.models import Permission, User

# Create your models here.

class TipoPorducto(models.Model):
    tipo = models.CharField(max_length=40)

    def __str__(self):
        return self.tipo

class Producto(models.Model):
    nombre = models.CharField(max_length=40)
    precio = models.IntegerField()
    descripcion = models.CharField(max_length=40)
    tipo = models.ForeignKey(TipoPorducto, on_delete=models.CASCADE)
    fecha = models.DateField()
    imagen = models.ImageField(null =True, blank=True)
    descuento = models.IntegerField()

    def __str__(self):
        return self.nombre

class Fundacion(models.Model):
    fundacion = models.CharField(max_length=40)
    monto_sub = models.IntegerField()
    descuento = models.IntegerField()
    def __str__(self):
        return self.fundacion

class Subscripcion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fundacion = models.ForeignKey(Fundacion, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario

#python manage.py makemigrations --- CREA EL ARCHIVO PARA MIGRAR
#python manage.py migrate --- ENVIA EL ARCHIVO A LA BD
#python manage.py createsuperuser --- CREA EL ADMIN EN LA WEB

"""
odd_even = Permission.objects.get(name='can_view_even_ids')
user_yui = User.objects.get(username='yui')
user_yui.user_permissions.add(odd_even)
user_yui.save()
"""

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BMMCjardineria</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/dist/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'app/dist/css/contacto.css' %}">
    <link rel="shortcut icon" href="{% static 'app/dist/img/logo.png' %}">
    <link rel="stylesheet" href="{% static 'app/dist/css/descuentos.css' %}">
    {% load %}

</head>
<body>
    
        <!-- header -->

        <!-- cuerpo de la pagina dividida -->
        <header>
            <div class="colorheader">    
                <nav>
                    <li><a href="{% url 'index' %}">INICIO</a></li>
                    <li><a href="{% url 'productos' %}">PRODUCTOS</a></li>
                    <li><a href="{% url 'contacto' %}">CONTACTOS</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">CERRAR SESION</a></li>
                    <li><a href="{% url 'subscripcion' %}">SUSCRIPCIONES</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESION</a></li>
                    {% endif %}
                    
                    {% if perms.view_producto %}
                    <li><a href="{% url 'tabla' %}">Admin</a></li>
                    {% else %}

                    {% endif %}
                    
                </nav>
            </div>
        </header>
        
        <div class="container-fluid">
            <div class="row">
              <div class="col-sm-3">
                <h3>Catalogo</h3>
                <div class="menu_izq"><li><a href="">{{ user.get_username }}</a></li></div>
                <div class="menu_izq"><li><a href="">Tierra de hoja</a></li></div>
                <div class="menu_izq"><li><a href="">Flores de verano</a></li></div>
                <div class="menu_izq"><li><a href="">Flores de otoño</a></li></div>
                <div class="menu_izq"><li><a href="">Flores de invierno</a></li></div>
                <div class="menu_izq"><li><a href="">Flores de primavera</a></li></div>
                <div class="menu_izq"><li><a href="">Maceteros</a></li></div>
              </div>
              <div class="col-sm-9 d-flex flex-wrap">
                {% block contenido %}
                
                {% endblock %}
              </div> 
            </div>
        </div>

        <!-- pie de pagina -->
        <footer class="contacto">
            <p class="redes">
                Instagram : <b>@BBMCjardineria</b> <br>
                Facebook : <b>BMMCjardineria</b> <br>
                Email : bmmcjardineria@gmail.com

            </p>
            <h1 class="copyright">BMMCjardinería - @Copyright - Todos los derechos reservados</h1>
        </footer>

</body>
{% block javascript %}

{% endblock %}
</html>

app/templates/app/contacto.html
{% extends 'app/base.html' %}
{% load static %}

{% block contenido %}
<div class="formcontacto">
    <h1>CONTACTO</h1>
    <div>
        <form class="dormulario">
            <div class="flex-lg-column">
                <div class="col">
                    <label for="nombre">Nombre</label>
                    <input type="text" class="form-control" placeholder="Ingresar nombre" name="nombre">
                  </div>
              <div class="col">
                  <label for="email">Email</label>
                  <input type="text" class="form-control" id="email" placeholder="Ingresar email" name="email">
              </div>
              <div class="col">
                  <label for="comentario">Comentario</label>
                  <input type="text" class="form-control" placeholder="Escribir comentario" name="comentario">
              </div>
              <div class="col">
                  <input type="submit" value="Enviar" class="btn btn_rojo btn_form">
              </div>
            </div>
        </form>
    </div>
    
</div>
{% endblock %}

app/templates/app/index.html
    {% extends 'app/base.html' %}
    {% load static %}

    {% block contenido %}
    
    <div class="container">
        <h3>Inicio</h3>
        <div>
            <P>Bienvenidos a la pagina de Jardineria BMMC</P>
        </div>
        <div class="logo">
            <img src="{% static 'app/dist/img/logo.png' %}" alt="">
        </div>
        
    </div>
    {% endblock %}

app/templates/app/ingreso.html
{% extends 'app/base.html' %}
{% load static %}

{% block contenido %}
<div class="container-fluid">
    <div class="row">
      <div class="col-sm-3"></div>
        <div class="col-sm-6">
        <h2 id="titulo-ingreso" >INGRESAR</h2>
        <form action="" method="POST">
          <div class="form-group">
            <label for="txtUsuario">Nombre De Usuario:</label>
            <input type="text" class="form-control" id="txtUsuario" placeholder="Ingrese Usuario" name="txtUsuario">
          </div>
          <div class="form-group">
            <label for="txtpass">Contrasena:</label>
            <input type="password" class="form-control" id="txtPass" placeholder="Ingrese Contraseña" name="txtPass">
          </div>
          <p>Si no tiene cuenta <a href="{% url 'registro' %}">Registrate.</a> </p>
          <button type="submit" class="btn btn-primary">Ingresar</button>
        </form>
      </div>
      <div class="col-sm-3"></div>

      <div class="col-sm-12">

        <div>
            <div class="logo">
                <img src="img/logo.png" alt="">
            </div>
            
        </div>
      </div>

    </div>
</div>
{% endblock %}

app/templates/app/paginator.html
{% if paginator.num_pages > 1%}

<div class="d-flex justify-content-center">

    <ul class="pagination">

        {% if lista.has_previous %}

            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ lista.previous_page_number }}#pagtable">Anterior</a></li>

        {% endif %}

        {% for page in paginator.page_range %}

            {% if forloop.last and page != lista.number and paginator.num_pages > 7 %} 

                {% if lista.next_page_number != paginator.num_pages%}

                <li class="page-item">

                    <a class="page-link" href="?page={{ lista.number | add:1}}#pagtable">...</a>

                </li>

                {% endif %}

            <li class="page-item">

                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>

            </li>

            {% endif %}

            {% if page == lista.number and page > 7 %}

            <li class="page-item">

                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>

            </li>    

            {% endif %}

            {% if page < 7 or page == lista.number %}

            <li class="page-item {% if page == lista.number %}active{% endif %}">

                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>

            </li>

            {% endif %}

        {% endfor %}

        {% if lista.has_next %}

            <li class="page-item d-none d-sm-block">

                <a class="page-link" href="?page={{ lista.next_page_number }}#pagtable">Siguiente</a>

            </li>

        {% endif %}

    </ul>

</div>

<div class="d-flex justify-content-center d-sm-none">            

    {% if lista.has_previous %}

        <span class="page-item"><a  class="page-link" href="?page={{ lista.previous_page_number }}#pagtable">Anterior</a></span>

    {% endif %}

    {% if lista.has_next %}

        <span class="page-item"><a class="page-link" href="?page={{ lista.next_page_number }}#pagtable">Siguiente</a></span>

    {% endif %}

    <br>

    <br>

</div>

{% endif %}

app/templates/app/productos.html
{% extends 'app/base.html' %}
{% load static %}

{% block contenido %}
    <div class="col-sm-12"><h1>INICIO</h1></div>
    <div class="conteiner d-flex flex-wrap">
        {% for aux in lista %}
        
        <div class="row">
            <div class="card" style="width:200px">
                <div class="contenedor-desc">
                    {% if perms.app.view_subscripcion %}
                    <p class="desc-sub">Descuento del 5% por ser Subscriptor.</p>
                    {% endif %}
                    {% if aux.descuento > 0 %}
                    <p class="desc-ind">Descuento induvidual del {{ aux.descuento }}%</p>
                    {% endif %}
                </div>
                {% if aux.imagen %}
                <img class="card-img" src="{{ aux.imagen.url }}" alt="Card image" width="50px" height="50px">
                {% else %}
                <img src="{% static 'app/dist/img/imagen-defecto.png' %}" alt="" width="50px" height="50px">
                {% endif %}
                <div class="card-body">
                    <h4 class="card-title">{{ aux.nombre }}</h4>
                    <p class="card-text">{{ aux.descripcion }}</p>
                    <p class="card-text h3">{{ aux.precio }}</p>
                    <a href="#" class="btn btn-primary">Comprar</a>
                </div>
            </div>

            
        </div>
        
        {% endfor %}
        </div>
        <div class="col-sm-12">
            {% include 'app/paginator.html' %}
        </div>

{% endblock %}

app/templates/app/registro.html
{% extends 'app/base.html' %}
{% load static %}

{% block contenido %}

<div class="formcontacto">
    <h1>REGISTRO</h1>
    <div>
        <form class="dormulario">
            <div class="flex-lg-column">
              <div class="col">
                  <label for="email">Email</label>
                  <input type="text" class="form-control" id="email" placeholder="Ingresar email" name="email">
              </div>
              <div class="col">
                  <label for="comentario">Contraseña</label>
                  <input type="password" class="form-control" placeholder="Escribir Contraseña" name="contraseña1">
              </div>
              <div class="col">
                  <label for="comentario">Repetir Contraseña</label>
                  <input type="password" class="form-control" placeholder="Repetir Contraseña" name="contraseña2">
              </div>
              <div class="col">
                  <input type="submit" value="Registrar" class="btn btn_rojo btn_form">
              </div>
            </div>
        </form>
    </div>
    
</div>

{% endblock %}